var age = 25;
age = true;
console.log(age);
age = 23;
console.log(age);
age = { 'name': 'mario', age: 33 };
console.log(age);
var mixed = [];
mixed.push(5);
mixed.push('luigi');
mixed.push(false);
console.log(mixed);
